### ISSUE TITLE
Connection fails when folder object exists in S3

### ISSUE THREAD

**Issue by swt2c** [timmyomahony/craft-remote-sync#64]
If your S3 bucket contains a folder "object", this causes Remote Sync to fail.  To reproduce:
1. Create a bucket.
2. Use AWS console to create a folder called "backup" in this bucket.
3. Configure Remote Sync to use this bucket.
4. Test connection - will fail.

If would be great if Remote Sync could ignore this object or report a better error message at least.

**Comment by swt2c** [comment]
In my case, I had created the `backup` folder, then copied some backups into that folder from another bucket, then tried to restore them.

**Comment by timmyomahony** [comment]
Apologies for the delay in following up here, but this should now be fixed in the latest Craft 5 release (via this commit https://github.com/timmyomahony/craft-remote-core/commit/271509a9d153b64d86c6b0e03d869c380e50e0e5)
